module.exports = {
  lang: 'el',
  title: 'Geomerchant',
  basemap: 'Υπόβαθρο',
  search: 'Αναζήτηση',
  // estateType:'Αγορά',
  sale: 'Αγορά',
  rent: 'Ενοικίαση',
  price: 'Τιμή',
  from: 'Από',
  to: 'Εώς',
  priceError: 'Η τιμή δεν είναι αριθμός!',
  estateCode: 'Κωδικός Ιδιοκτησίας',
  estateProperties: 'Χαρακτηριστικά Ακινήτου',
  chooseArea: 'Επιλογή Περιοχής για Αναζήτηση',
  type: 'Τύπος',
  area: 'Εμβαδό',
  address: 'Διευθυνση',
  bedrooms: 'Υπνοδωμάτια',
  newbuild: 'Νεόδμητο',
  parking: 'Στάθμεση',
  furnished: 'Επιπλωμένο',
  pets: 'Κατοικίδια',
  view: 'Θέα',
  heating: 'Θέρμανση',
  cooling: 'Κλιματισμός',
  contactInfo: 'Στοιχεία Επικοινωνίας',
  name: 'Όνομα',
  lastname: 'Επίθετο',
  phone: 'Τηλέφωνο',
  email: 'Ηλεκτρονική Διεύθυνση',
  btns: {
    estateProperties: 'Επιλέξτε Χαρακτηριστικά Ακινήτου',
    chooseArea: 'Αναζήτηση Βάση Περιοχής στο Χάρτη',
    clear: 'Καθαρισμός',
    search: 'Αναζήτηση',
    login: 'Σύνδεση',
    insert: 'Εισαγωγή',
    delete: 'Διαγραφή',
    edit: 'Επεξεργασία',
    logout: 'Αποσύνδεση',
    update: 'Ενημέρωση',
    advancedFilters: 'Περισσότερα Κριτήρια',
    info: 'Πληροφορίες',
    close: 'Κλείσιμο',
    enterFullscreen: 'Πλήρης Οθόνη',
    exitFullscreen: 'Έξοδος από Πληρη Οθόνη'
  }
};
