module.exports = {
  lang: 'en',
  title: 'Geomerchant',
  basemap: 'BaseMap',
  search: 'Search',
  sale: 'Buy',
  rent: 'Rent',
  price: 'Price',
  from: 'From',
  to: 'To',
  priceError: 'Input is not a number!',
  estateCode: 'Estate Code',
  estateProperties: 'Estate Properites',
  chooseArea: 'Choose Area of Search',
  type: 'Type',
  area: 'Size',
  address: 'Address',
  bedrooms: 'Bedrooms',
  newbuild: 'Newly Build',
  parking: 'Parking',
  furnished: 'Furnished',
  pets: 'Pets Allowed',
  view: 'View',
  heating: 'Heating',
  cooling: 'Air Condition',
  contactInfo: 'Contact Info',
  name: 'Name',
  lastname: 'Last Name',
  phone: 'Telephone',
  email: 'Email',
  btns: {
    insert: 'insert',
    delete: 'delete',
    update: 'update',
    logout: 'logout'
  }
};
