module.exports = {
  lang: 'el',
  title: 'Geomerchant',
  basemap: 'Υπόβαθρο',
  btns: {
    clear: 'Καθαρισμός',
    search: 'Αναζήτηση',
    sale: 'Αγορά',
    rent: 'Ενοικίαση',
    parking: 'Στάθμεση',
    furnished: 'Επιπλωμένο',
    pets: 'Κατοικίδια',
    view: 'Θέα',
    heating: 'Θέρμανση',
    cooling: 'Κλιματισμός',
    newbuild: 'Νεόδμητο',
    insert: 'εισαγωγη',
    delete: 'διαγραφη',
    update: 'ενημερωση',
    logout: 'αποσυνδεση',
    advancedFilters: 'Περισσότερα Κριτήρια'
  },
  price: 'Τιμή',
  from: 'από',
  to: 'εώς',
  andMore: 'και πάνω',
  priceError: 'Η τιμή δεν είναι αριθμός!',
  estateCode: 'Κωδικός Ιδιοκτησίας',
  estateProperties: 'Επιλέξτε Χαρακτηριστικά Ακινήτου',
  chooseArea: 'Επιλογή Περιοχής για Αναζήτηση',
  listingType: 'Είδος Αγγελίας',
  estate: {
    title: 'Τύπος Ιδιοκτησίας',
    type: {
      detached: 'Μονοκατοικία',
      apartment: 'Διαμέρισμα',
      store: 'Κατάστημα',
      maisonette: 'Μεζονέτα',
      villa: 'Έπαυλη'
    }
  },
  area: 'Εμβαδό',
  address: 'Διευθυνση',
  bedrooms: 'Υπνοδωμάτια',
  contactInfo: 'Στοιχεία Επικοινωνίας',
  name: 'Όνομα',
  lastname: 'Επίθετο',
  phone: 'Τηλέφωνο',
  email: 'Ηλεκτρονική Διεύθυνση'
};
