module.exports = {
  lang: 'en',
  title: 'Geomerchant',
  basemap: 'BaseMap',
  btns: {
    clear: 'Clear',
    search: 'Search',
    sale: 'Buy',
    rent: 'Rent',
    parking: 'Parking',
    furnished: 'Furnished',
    pets: 'Pets Allowed',
    view: 'View',
    heating: 'Heating',
    cooling: 'Air Condition',
    newbuild: 'Newly Build',
    insert: 'insert',
    delete: 'delete',
    update: 'update',
    logout: 'logout',
    advancedFilters: 'Advanced Filters'
  },
  priceTitle: 'Choose Estate Price',
  price: 'Price',
  from: 'From',
  to: 'To',
  andMore: 'and more',
  or: 'or Enter Price',
  priceError: 'Input is not a number!',
  estateCode: 'Estate Code',
  estateProperties: 'Choose Estate Properites',
  chooseArea: 'Search By Map Area',
  listingType: 'Listing Type',
  estate: {
    title: 'Estate Type',
    type: {
      detached: 'Detached House',
      apartment: 'Apartment',
      store: 'Store',
      maisonette: 'Maisonette',
      villa: 'Villa'
    }
  },
  area: 'Size',
  address: 'Address',
  bedrooms: 'Bedrooms',
  contactInfo: 'Contact Info',
  name: 'Name',
  lastname: 'Last Name',
  phone: 'Telephone'
};
